version: "3.9"
services:
    tinurlserver:
        build: ./server/
        ports: 
            - 3001:3001

    redis:
        image: redis
        ports:
            - 6379:6379
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ~/mongo/data:/data/db
    
    tinurlclient:
        build: ./Client/
        ports: 
            - 3000:3000
        


            
